version: '2.2'

services:
    rating-service:
        image: rating-service
        container_name: rating-service
        build:
            context: ./api
            dockerfile: Dockerfile
            args:
                - APP_DIR=rating-service
        ports:
            - "8081:8080"
        mem_limit: 160m
    booking-service:
        image: booking-service
        container_name: booking-service
        build:
            context: ./api
            dockerfile: Dockerfile
            args:
                - APP_DIR=booking-service
        ports:
            - "8082:8080"
        mem_limit: 160m
    user-service:
        image: user-service
        container_name: user-service
        build:
            context: ./api
            dockerfile: Dockerfile
            args:
                - APP_DIR=user-service
        ports:
            - "8083:8080"
        mem_limit: 160m
    vehicle-service:
        image: vehicle-service
        container_name: vehicle-service
        build:
            context: ./api
            dockerfile: Dockerfile
            args:
                - APP_DIR=vehicle-service
        ports:
            - "8084:8080"
        mem_limit: 160m
    auth-service:
        image: auth-service
        container_name: auth-service
        build:
            context: ./api
            dockerfile: Dockerfile
            args:
                - APP_DIR=auth-service
        ports:
            - "8085:8080"
        mem_limit: 160m
    amqp-broker:
        image: amqp-broker
        container_name: amqp-broker
        build:
            context: ./api
            dockerfile: Dockerfile
            args:
                - APP_DIR=auth-service
        ports:
            - "8086:8080"
        mem_limit: 160m
    mail-service:
        image: amqp-broker
        container_name: amqp-broker
        build:
            context: ./api
            dockerfile: Dockerfile
            args:
                - APP_DIR=mail-service
        ports:
            - "8087:8080"
        mem_limit: 160m
    storage-service-stub:
        image: storage-service-stub
        container_name: storage-service-stub
        build:
            context: ./api
            dockerfile: Dockerfile
            args:
                - APP_DIR=storage-service-stub
        ports:
            - "8088:8080"
        mem_limit: 160m
