export const profileLink: string = '/profile';
export const loginLink: string = '/login';
export const logoutLink: string = '/logout';
export const registrationLink: string = '/registration';
export const homeLink: string = '/';
export const carListLink: string = '/car-list';
export const carListPageableLink: string = '/car-list?page=:page';
export const bestOffersLink: string = '/best-offers';
export const bestOffersPageableLink: string = '/best-offers?page=:page';
export const carDetailsLink: string = '/car-details/:carId';
export const carDetailsByIdLink = (carId: number):string => `/car-details/${carId}`;
export const aboutUsLink: string = '/about-us';
export const contactLink: string = '/contact';
