export const profileLink = '/profile';
export const loginLink = '/login';
export const logoutLink = '/logout';
export const registrationLink = '/registration';
export const homeLink = '/';
export const carListLink = '/car-list';
export const carListPageableLink = '/car-list?page=:page';
export const bestOffersLink = '/best-offers';
export const bestOffersPageableLink = '/best-offers?page=:page';
export const carDetailsLink = '/car-details/:carId';
export const carDetailsByIdLink = (carId: number): string => `/car-details/${carId}`;
export const aboutUsLink = '/about-us';
export const contactLink = '/contact';
